# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0002_studentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=2),
        ),
    ]
