# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0003_studentinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(choices=[('ma', 'Male'), ('fe', 'Female')], default='ma', max_length=20),
        ),
    ]
